import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePackageFirstSchema20260426141000 implements MigrationInterface {
  name = 'CreatePackageFirstSchema20260426141000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TABLE tai_khoan (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  email VARCHAR(191) NOT NULL,\n  mat_khau_ma_hoa VARCHAR(255) NOT NULL,\n  vai_tro ENUM('customer', 'expert', 'admin') NOT NULL,\n  trang_thai ENUM('hoat_dong', 'khong_hoat_dong', 'bi_khoa') NOT NULL DEFAULT 'hoat_dong',\n  ho_ten VARCHAR(150) NOT NULL,\n  so_dien_thoai VARCHAR(30) NULL,\n  ma_dat_lai_mat_khau VARCHAR(255) NULL,\n  het_han_ma_dat_lai DATETIME NULL,\n  dang_nhap_cuoi_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  xoa_luc DATETIME NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_tai_khoan_email (email),\n  KEY idx_tai_khoan_vai_tro_trang_thai (vai_tro, trang_thai)\n)");
    await queryRunner.query("CREATE TABLE ho_so_customer (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  gioi_tinh ENUM('nam', 'nu', 'khac') NULL,\n  ngay_sinh DATE NULL,\n  anh_dai_dien_url VARCHAR(500) NULL,\n  ghi_chu_suc_khoe TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_ho_so_customer_tai_khoan (tai_khoan_id),\n  CONSTRAINT fk_ho_so_customer_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE ho_so_suc_khoe (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  gioi_tinh ENUM('nam', 'nu', 'khac') NULL,\n  ngay_sinh DATE NULL,\n  chieu_cao_cm DECIMAL(10,2) NULL,\n  can_nang_hien_tai_kg DECIMAL(10,2) NULL,\n  muc_do_van_dong ENUM('it_van_dong', 'van_dong_nhe', 'van_dong_vua', 'nang_dong', 'rat_nang_dong') NULL,\n  muc_tieu_suc_khoe ENUM('giam_can', 'tang_can', 'giu_can', 'cai_thien_suc_khoe') NULL,\n  tinh_trang_suc_khoe JSON NULL,\n  di_ung JSON NULL,\n  che_do_an_uu_tien JSON NULL,\n  thuc_pham_khong_dung JSON NULL,\n  ghi_chu_cho_chuyen_gia TEXT NULL,\n  da_hoan_thanh TINYINT(1) NOT NULL DEFAULT 0,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_ho_so_suc_khoe_tai_khoan (tai_khoan_id),\n  CONSTRAINT fk_ho_so_suc_khoe_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE chi_so_suc_khoe (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  do_luc DATETIME NOT NULL,\n  can_nang_kg DECIMAL(10,2) NULL,\n  vong_eo_cm DECIMAL(10,2) NULL,\n  vong_mong_cm DECIMAL(10,2) NULL,\n  huyet_ap_tam_thu SMALLINT UNSIGNED NULL,\n  huyet_ap_tam_truong SMALLINT UNSIGNED NULL,\n  nhip_tim SMALLINT UNSIGNED NULL,\n  duong_huyet DECIMAL(10,2) NULL,\n  chat_luong_giac_ngu INT UNSIGNED NULL,\n  muc_nang_luong INT UNSIGNED NULL,\n  bmi DECIMAL(10,2) NULL,\n  canh_bao JSON NULL,\n  ghi_chu TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  xoa_luc DATETIME NULL,\n  PRIMARY KEY (id),\n  KEY idx_chi_so_suc_khoe_tai_khoan_do_luc (tai_khoan_id, do_luc),\n  CONSTRAINT fk_chi_so_suc_khoe_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE otp (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  email VARCHAR(191) NOT NULL,\n  ma_otp VARCHAR(255) NOT NULL,\n  loai ENUM('xac_thuc', 'dat_lai_mat_khau') NOT NULL,\n  da_su_dung TINYINT(1) NOT NULL DEFAULT 0,\n  het_han_luc DATETIME NOT NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_otp_email_loai_su_dung (email, loai, da_su_dung)\n)");
    await queryRunner.query("CREATE TABLE chuyen_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  chuyen_mon TEXT NULL,\n  mo_ta TEXT NULL,\n  kinh_nghiem TEXT NULL,\n  hoc_vi VARCHAR(150) NULL,\n  chung_chi TEXT NULL,\n  anh_dai_dien_url VARCHAR(500) NULL,\n  trang_thai ENUM('cho_duyet', 'tu_choi', 'hoat_dong', 'tam_dung', 'bi_khoa') NOT NULL DEFAULT 'cho_duyet',\n  nhan_booking TINYINT(1) NOT NULL DEFAULT 1,\n  diem_danh_gia_trung_binh DECIMAL(3,2) NOT NULL DEFAULT 0,\n  so_luot_danh_gia INT UNSIGNED NOT NULL DEFAULT 0,\n  so_booking_hoan_thanh INT UNSIGNED NOT NULL DEFAULT 0,\n  ly_do_tu_choi TEXT NULL,\n  ly_do_bi_khoa TEXT NULL,\n  duyet_boi BIGINT UNSIGNED NULL,\n  duyet_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  xoa_luc DATETIME NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_chuyen_gia_tai_khoan (tai_khoan_id),\n  KEY idx_chuyen_gia_trang_thai_nhan_booking (trang_thai, nhan_booking),\n  CONSTRAINT fk_chuyen_gia_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_chuyen_gia_duyet_boi FOREIGN KEY (duyet_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE goi_dich_vu (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ma_goi VARCHAR(50) NOT NULL,\n  ten_goi VARCHAR(150) NOT NULL,\n  slug VARCHAR(180) NOT NULL,\n  loai_goi ENUM('suc_khoe', 'dinh_duong', 'tap_luyen') NOT NULL,\n  mo_ta TEXT NULL,\n  quyen_loi JSON NULL,\n  gia DECIMAL(12,2) NOT NULL DEFAULT 0,\n  gia_khuyen_mai DECIMAL(12,2) NULL,\n  thoi_han_ngay INT UNSIGNED NOT NULL DEFAULT 30,\n  so_luot_tu_van INT UNSIGNED NOT NULL DEFAULT 1,\n  thoi_luong_tu_van_phut INT UNSIGNED NOT NULL DEFAULT 30,\n  trang_thai ENUM('ban_nhap', 'dang_ban', 'ngung_ban') NOT NULL DEFAULT 'ban_nhap',\n  goi_noi_bat TINYINT(1) NOT NULL DEFAULT 0,\n  thu_tu_hien_thi INT UNSIGNED NOT NULL DEFAULT 1,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  xoa_luc DATETIME NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_goi_dich_vu_ma_goi (ma_goi),\n  UNIQUE KEY uq_goi_dich_vu_slug (slug),\n  KEY idx_goi_dich_vu_loai_trang_thai (loai_goi, trang_thai)\n)");
    await queryRunner.query("CREATE TABLE goi_dich_vu_chuyen_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  goi_dich_vu_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  trang_thai ENUM('hoat_dong', 'tam_dung') NOT NULL DEFAULT 'hoat_dong',\n  ty_le_hoa_hong_override DECIMAL(5,2) NULL,\n  gan_boi BIGINT UNSIGNED NULL,\n  gan_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_goi_chuyen_gia (goi_dich_vu_id, chuyen_gia_id),\n  KEY idx_goi_chuyen_gia_chuyen_gia (chuyen_gia_id, trang_thai),\n  CONSTRAINT fk_goi_chuyen_gia_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_goi_chuyen_gia_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_goi_chuyen_gia_gan_boi FOREIGN KEY (gan_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE goi_da_mua (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  goi_dich_vu_id BIGINT UNSIGNED NOT NULL,\n  ma_goi_da_mua VARCHAR(80) NOT NULL,\n  trang_thai ENUM('cho_thanh_toan', 'dang_hieu_luc', 'het_luot', 'het_han', 'tam_khoa', 'da_hoan_tien') NOT NULL DEFAULT 'cho_thanh_toan',\n  gia_mua DECIMAL(12,2) NOT NULL DEFAULT 0,\n  so_luot_tong INT UNSIGNED NOT NULL,\n  so_luot_da_dung INT UNSIGNED NOT NULL DEFAULT 0,\n  so_luot_con_lai INT UNSIGNED NOT NULL,\n  bat_dau_luc DATETIME NULL,\n  het_han_luc DATETIME NULL,\n  khoa_luc DATETIME NULL,\n  ly_do_khoa TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_goi_da_mua_ma (ma_goi_da_mua),\n  KEY idx_goi_da_mua_tai_khoan_trang_thai (tai_khoan_id, trang_thai),\n  KEY idx_goi_da_mua_goi_trang_thai (goi_dich_vu_id, trang_thai),\n  CONSTRAINT fk_goi_da_mua_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_goi_da_mua_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE lich_su_su_dung_goi (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  goi_da_mua_id BIGINT UNSIGNED NOT NULL,\n  lich_hen_id BIGINT UNSIGNED NULL,\n  loai_su_kien ENUM('giu_luot', 'tru_luot', 'hoan_luot', 'het_han', 'tam_khoa') NOT NULL,\n  so_luot_thay_doi INT NOT NULL DEFAULT 0,\n  so_luot_con_lai_sau INT UNSIGNED NOT NULL DEFAULT 0,\n  ghi_chu TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_lich_su_su_dung_goi (goi_da_mua_id, tao_luc),\n  CONSTRAINT fk_lich_su_su_dung_goi_goi_da_mua FOREIGN KEY (goi_da_mua_id) REFERENCES goi_da_mua(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE thanh_toan (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  loai_thanh_toan ENUM('mua_goi', 'booking') NOT NULL,\n  doi_tuong_id BIGINT UNSIGNED NOT NULL,\n  ma_giao_dich VARCHAR(150) NOT NULL,\n  cong_thanh_toan ENUM('vnpay', 'chuyen_khoan', 'thu_cong', 'mien_phi') NOT NULL DEFAULT 'vnpay',\n  so_tien DECIMAL(12,2) NOT NULL,\n  tien_te VARCHAR(10) NOT NULL DEFAULT 'VND',\n  trang_thai ENUM('khoi_tao', 'cho_thanh_toan', 'thanh_cong', 'that_bai', 'het_han', 'hoan_tien') NOT NULL DEFAULT 'khoi_tao',\n  payment_url TEXT NULL,\n  txn_ref VARCHAR(150) NULL,\n  gateway_transaction_no VARCHAR(150) NULL,\n  raw_request JSON NULL,\n  raw_response JSON NULL,\n  thanh_toan_luc DATETIME NULL,\n  het_han_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_thanh_toan_ma_giao_dich (ma_giao_dich),\n  UNIQUE KEY uq_thanh_toan_txn_ref (txn_ref),\n  KEY idx_thanh_toan_tai_khoan (tai_khoan_id, trang_thai, tao_luc),\n  KEY idx_thanh_toan_doi_tuong (loai_thanh_toan, doi_tuong_id),\n  CONSTRAINT fk_thanh_toan_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE payment_webhook_log (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  thanh_toan_id BIGINT UNSIGNED NULL,\n  txn_ref VARCHAR(150) NULL,\n  loai_webhook ENUM('return', 'ipn') NOT NULL,\n  hop_le TINYINT(1) NOT NULL DEFAULT 0,\n  payload JSON NOT NULL,\n  ket_qua_xu_ly JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_payment_webhook_txn_ref (txn_ref, tao_luc),\n  CONSTRAINT fk_payment_webhook_thanh_toan FOREIGN KEY (thanh_toan_id) REFERENCES thanh_toan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE refund (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  thanh_toan_id BIGINT UNSIGNED NOT NULL,\n  so_tien DECIMAL(12,2) NOT NULL,\n  ly_do TEXT NOT NULL,\n  trang_thai ENUM('yeu_cau', 'dang_xu_ly', 'thanh_cong', 'that_bai', 'tu_choi') NOT NULL DEFAULT 'yeu_cau',\n  xu_ly_boi BIGINT UNSIGNED NULL,\n  xu_ly_luc DATETIME NULL,\n  raw_response JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_refund_thanh_toan (thanh_toan_id, trang_thai),\n  CONSTRAINT fk_refund_thanh_toan FOREIGN KEY (thanh_toan_id) REFERENCES thanh_toan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_refund_xu_ly_boi FOREIGN KEY (xu_ly_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE lich_lam_viec_chuyen_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  thu_trong_tuan TINYINT UNSIGNED NOT NULL COMMENT '1=Monday, 7=Sunday',\n  gio_bat_dau TIME NOT NULL,\n  gio_ket_thuc TIME NOT NULL,\n  thoi_luong_slot_phut INT UNSIGNED NOT NULL DEFAULT 30,\n  trang_thai ENUM('hoat_dong', 'tam_dung') NOT NULL DEFAULT 'hoat_dong',\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_lich_lam_viec_chuyen_gia (chuyen_gia_id, thu_trong_tuan, trang_thai),\n  CONSTRAINT fk_lich_lam_viec_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE lich_ban_chuyen_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  bat_dau_luc DATETIME NOT NULL,\n  ket_thuc_luc DATETIME NOT NULL,\n  ly_do TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_lich_ban_chuyen_gia (chuyen_gia_id, bat_dau_luc, ket_thuc_luc),\n  CONSTRAINT fk_lich_ban_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE lich_hen (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ma_lich_hen VARCHAR(80) NOT NULL,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  goi_dich_vu_id BIGINT UNSIGNED NOT NULL,\n  goi_da_mua_id BIGINT UNSIGNED NOT NULL,\n  thanh_toan_id BIGINT UNSIGNED NULL,\n  muc_dich TEXT NULL,\n  ghi_chu_customer TEXT NULL,\n  ngay_hen DATE NOT NULL,\n  gio_bat_dau TIME NOT NULL,\n  gio_ket_thuc TIME NOT NULL,\n  bat_dau_luc DATETIME NOT NULL,\n  ket_thuc_luc DATETIME NOT NULL,\n  trang_thai ENUM('cho_xac_nhan', 'cho_thanh_toan', 'da_xac_nhan', 'da_checkin', 'dang_tu_van', 'hoan_thanh', 'da_huy', 'vo_hieu_hoa') NOT NULL DEFAULT 'cho_xac_nhan',\n  giu_cho_den_luc DATETIME NULL,\n  ly_do_huy TEXT NULL,\n  huy_boi BIGINT UNSIGNED NULL,\n  huy_luc DATETIME NULL,\n  hoan_thanh_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_lich_hen_ma (ma_lich_hen),\n  KEY idx_lich_hen_customer_ngay (tai_khoan_id, ngay_hen, trang_thai),\n  KEY idx_lich_hen_chuyen_gia_ngay (chuyen_gia_id, ngay_hen, trang_thai),\n  KEY idx_lich_hen_goi_da_mua (goi_da_mua_id, trang_thai),\n  CONSTRAINT fk_lich_hen_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_lich_hen_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_lich_hen_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_lich_hen_goi_da_mua FOREIGN KEY (goi_da_mua_id) REFERENCES goi_da_mua(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_lich_hen_thanh_toan FOREIGN KEY (thanh_toan_id) REFERENCES thanh_toan(id) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT fk_lich_hen_huy_boi FOREIGN KEY (huy_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE booking_timeline (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  actor_id BIGINT UNSIGNED NULL,\n  su_kien VARCHAR(80) NOT NULL,\n  trang_thai_truoc VARCHAR(50) NULL,\n  trang_thai_sau VARCHAR(50) NULL,\n  ghi_chu TEXT NULL,\n  metadata JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_booking_timeline_lich_hen (lich_hen_id, tao_luc),\n  CONSTRAINT fk_booking_timeline_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_booking_timeline_actor FOREIGN KEY (actor_id) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("ALTER TABLE lich_su_su_dung_goi\n  ADD CONSTRAINT fk_lich_su_su_dung_goi_lich_hen\n  FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE SET NULL ON UPDATE CASCADE");
    await queryRunner.query("CREATE TABLE ghi_chu_tu_van (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  tom_tat_cho_customer TEXT NULL,\n  ghi_chu_noi_bo TEXT NULL,\n  khuyen_nghi_sau_tu_van TEXT NULL,\n  tags JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_ghi_chu_tu_van_lich_hen (lich_hen_id),\n  CONSTRAINT fk_ghi_chu_tu_van_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_ghi_chu_tu_van_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE tin_nhan (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  nguoi_gui_id BIGINT UNSIGNED NOT NULL,\n  loai ENUM('text', 'file') NOT NULL DEFAULT 'text',\n  noi_dung TEXT NULL,\n  tep_dinh_kem JSON NULL,\n  da_doc_luc DATETIME NULL,\n  da_doc_boi_id BIGINT UNSIGNED NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_tin_nhan_lich_hen_tao_luc (lich_hen_id, tao_luc),\n  CONSTRAINT fk_tin_nhan_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_tin_nhan_nguoi_gui FOREIGN KEY (nguoi_gui_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_tin_nhan_da_doc_boi FOREIGN KEY (da_doc_boi_id) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE cuoc_goi_tu_van (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  provider ENUM('livekit', 'jitsi', 'external') NOT NULL DEFAULT 'livekit',\n  room_name VARCHAR(150) NOT NULL,\n  trang_thai ENUM('cho', 'dang_dien_ra', 'ket_thuc', 'bi_huy') NOT NULL DEFAULT 'cho',\n  bat_dau_luc DATETIME NULL,\n  ket_thuc_luc DATETIME NULL,\n  thoi_luong_giay INT UNSIGNED NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_cuoc_goi_lich_hen (lich_hen_id),\n  UNIQUE KEY uq_cuoc_goi_room_name (room_name),\n  CONSTRAINT fk_cuoc_goi_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE danh_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  diem INT UNSIGNED NOT NULL,\n  noi_dung TEXT NULL,\n  tags JSON NULL,\n  trang_thai ENUM('hien_thi', 'bi_an', 'bi_bao_cao', 'da_xoa') NOT NULL DEFAULT 'hien_thi',\n  an_boi BIGINT UNSIGNED NULL,\n  an_luc DATETIME NULL,\n  ly_do_an TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_danh_gia_lich_hen (lich_hen_id),\n  KEY idx_danh_gia_chuyen_gia (chuyen_gia_id, trang_thai, tao_luc),\n  CONSTRAINT fk_danh_gia_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_danh_gia_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_danh_gia_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_danh_gia_an_boi FOREIGN KEY (an_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE phan_hoi_danh_gia (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  danh_gia_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  noi_dung TEXT NOT NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_phan_hoi_danh_gia (danh_gia_id),\n  CONSTRAINT fk_phan_hoi_danh_gia FOREIGN KEY (danh_gia_id) REFERENCES danh_gia(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_phan_hoi_danh_gia_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE phien_chat_ai (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  tieu_de VARCHAR(191) NULL,\n  loai_context ENUM('suc_khoe', 'dinh_duong', 'tap_luyen', 'tu_van_chung') NOT NULL DEFAULT 'suc_khoe',\n  context_snapshot JSON NULL,\n  trang_thai ENUM('dang_mo', 'da_luu_tru') NOT NULL DEFAULT 'dang_mo',\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_phien_chat_ai_tai_khoan (tai_khoan_id, trang_thai, cap_nhat_luc),\n  CONSTRAINT fk_phien_chat_ai_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE tin_nhan_chat_ai (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  phien_chat_ai_id BIGINT UNSIGNED NOT NULL,\n  vai_tro ENUM('user', 'assistant', 'system') NOT NULL,\n  noi_dung MEDIUMTEXT NOT NULL,\n  model VARCHAR(100) NULL,\n  token_input INT UNSIGNED NULL,\n  token_output INT UNSIGNED NULL,\n  trang_thai ENUM('thanh_cong', 'that_bai') NOT NULL DEFAULT 'thanh_cong',\n  loi TEXT NULL,\n  metadata JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_tin_nhan_chat_ai_phien (phien_chat_ai_id, tao_luc),\n  CONSTRAINT fk_tin_nhan_chat_ai_phien FOREIGN KEY (phien_chat_ai_id) REFERENCES phien_chat_ai(id) ON DELETE CASCADE ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE goi_y_suc_khoe (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  phien_chat_ai_id BIGINT UNSIGNED NULL,\n  loai_goi_y ENUM('ke_hoach_suc_khoe', 'canh_bao_suc_khoe') NOT NULL DEFAULT 'ke_hoach_suc_khoe',\n  input_snapshot JSON NOT NULL,\n  noi_dung_goi_y JSON NOT NULL,\n  muc_do_uu_tien ENUM('thap', 'trung_binh', 'cao') NOT NULL DEFAULT 'trung_binh',\n  canh_bao JSON NULL,\n  ly_do TEXT NULL,\n  trang_thai ENUM('moi_tao', 'da_ap_dung', 'luu_tru') NOT NULL DEFAULT 'moi_tao',\n  ap_dung_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_goi_y_suc_khoe_tai_khoan (tai_khoan_id, trang_thai, tao_luc),\n  CONSTRAINT fk_goi_y_suc_khoe_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_goi_y_suc_khoe_phien_chat FOREIGN KEY (phien_chat_ai_id) REFERENCES phien_chat_ai(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE goi_y_dinh_duong_tap_luyen (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  phien_chat_ai_id BIGINT UNSIGNED NULL,\n  input_snapshot JSON NOT NULL,\n  muc_tieu_calories DECIMAL(10,2) NULL,\n  muc_tieu_protein_g DECIMAL(10,2) NULL,\n  muc_tieu_carb_g DECIMAL(10,2) NULL,\n  muc_tieu_fat_g DECIMAL(10,2) NULL,\n  goi_y_dinh_duong JSON NULL,\n  goi_y_tap_luyen JSON NULL,\n  canh_bao JSON NULL,\n  ly_do TEXT NULL,\n  trang_thai ENUM('moi_tao', 'da_ap_dung', 'luu_tru') NOT NULL DEFAULT 'moi_tao',\n  ap_dung_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_goi_y_dinh_duong_tap_luyen_tai_khoan (tai_khoan_id, trang_thai, tao_luc),\n  CONSTRAINT fk_goi_y_dinh_duong_tap_luyen_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_goi_y_dinh_duong_tap_luyen_phien_chat FOREIGN KEY (phien_chat_ai_id) REFERENCES phien_chat_ai(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE cau_hinh_hoa_hong (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  pham_vi ENUM('he_thong', 'goi_dich_vu', 'chuyen_gia', 'goi_chuyen_gia') NOT NULL,\n  goi_dich_vu_id BIGINT UNSIGNED NULL,\n  chuyen_gia_id BIGINT UNSIGNED NULL,\n  ty_le_hoa_hong DECIMAL(5,2) NOT NULL DEFAULT 30.00,\n  hieu_luc_tu DATE NOT NULL,\n  hieu_luc_den DATE NULL,\n  trang_thai ENUM('hoat_dong', 'ngung_ap_dung') NOT NULL DEFAULT 'hoat_dong',\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_cau_hinh_hoa_hong_scope (pham_vi, goi_dich_vu_id, chuyen_gia_id, trang_thai),\n  CONSTRAINT fk_cau_hinh_hoa_hong_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT fk_cau_hinh_hoa_hong_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE ky_hoa_hong (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ma_ky VARCHAR(30) NOT NULL,\n  thang TINYINT UNSIGNED NOT NULL,\n  nam SMALLINT UNSIGNED NOT NULL,\n  tu_ngay DATE NOT NULL,\n  den_ngay DATE NOT NULL,\n  trang_thai ENUM('nhap', 'da_chot', 'da_chi_tra') NOT NULL DEFAULT 'nhap',\n  tong_doanh_thu_hop_le DECIMAL(14,2) NOT NULL DEFAULT 0,\n  tong_hoa_hong DECIMAL(14,2) NOT NULL DEFAULT 0,\n  chot_boi BIGINT UNSIGNED NULL,\n  chot_luc DATETIME NULL,\n  chi_tra_boi BIGINT UNSIGNED NULL,\n  chi_tra_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_ky_hoa_hong_ma_ky (ma_ky),\n  UNIQUE KEY uq_ky_hoa_hong_thang_nam (thang, nam),\n  CONSTRAINT fk_ky_hoa_hong_chot_boi FOREIGN KEY (chot_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT fk_ky_hoa_hong_chi_tra_boi FOREIGN KEY (chi_tra_boi) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE chi_tiet_hoa_hong (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ky_hoa_hong_id BIGINT UNSIGNED NOT NULL,\n  lich_hen_id BIGINT UNSIGNED NOT NULL,\n  thanh_toan_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  goi_dich_vu_id BIGINT UNSIGNED NOT NULL,\n  doanh_thu_hop_le DECIMAL(12,2) NOT NULL,\n  ty_le_hoa_hong DECIMAL(5,2) NOT NULL DEFAULT 30.00,\n  so_tien_hoa_hong DECIMAL(12,2) NOT NULL,\n  trang_thai ENUM('nhap', 'da_chot', 'da_huy') NOT NULL DEFAULT 'nhap',\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_chi_tiet_hoa_hong_lich_hen (lich_hen_id),\n  KEY idx_chi_tiet_hoa_hong_ky_chuyen_gia (ky_hoa_hong_id, chuyen_gia_id),\n  CONSTRAINT fk_chi_tiet_hoa_hong_ky FOREIGN KEY (ky_hoa_hong_id) REFERENCES ky_hoa_hong(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_chi_tiet_hoa_hong_lich_hen FOREIGN KEY (lich_hen_id) REFERENCES lich_hen(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_chi_tiet_hoa_hong_thanh_toan FOREIGN KEY (thanh_toan_id) REFERENCES thanh_toan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_chi_tiet_hoa_hong_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_chi_tiet_hoa_hong_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES goi_dich_vu(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE chi_tra_hoa_hong (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ky_hoa_hong_id BIGINT UNSIGNED NOT NULL,\n  chuyen_gia_id BIGINT UNSIGNED NOT NULL,\n  so_booking INT UNSIGNED NOT NULL DEFAULT 0,\n  tong_doanh_thu_hop_le DECIMAL(14,2) NOT NULL DEFAULT 0,\n  tong_hoa_hong DECIMAL(14,2) NOT NULL DEFAULT 0,\n  trang_thai ENUM('cho_chi_tra', 'da_chi_tra', 'that_bai') NOT NULL DEFAULT 'cho_chi_tra',\n  phuong_thuc_chi_tra VARCHAR(80) NULL,\n  ma_chi_tra VARCHAR(120) NULL,\n  ghi_chu TEXT NULL,\n  chi_tra_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_chi_tra_hoa_hong_ky_chuyen_gia (ky_hoa_hong_id, chuyen_gia_id),\n  CONSTRAINT fk_chi_tra_hoa_hong_ky FOREIGN KEY (ky_hoa_hong_id) REFERENCES ky_hoa_hong(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_chi_tra_hoa_hong_chuyen_gia FOREIGN KEY (chuyen_gia_id) REFERENCES chuyen_gia(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE khieu_nai (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  ma_khieu_nai VARCHAR(80) NOT NULL,\n  nguoi_gui_id BIGINT UNSIGNED NOT NULL,\n  loai_khieu_nai ENUM('booking', 'thanh_toan', 'danh_gia', 'khac') NOT NULL,\n  doi_tuong_id BIGINT UNSIGNED NULL,\n  tieu_de VARCHAR(191) NOT NULL,\n  noi_dung TEXT NOT NULL,\n  muc_uu_tien ENUM('thap', 'trung_binh', 'cao') NOT NULL DEFAULT 'trung_binh',\n  trang_thai ENUM('moi', 'dang_xu_ly', 'cho_phan_hoi', 'da_giai_quyet', 'da_dong') NOT NULL DEFAULT 'moi',\n  gan_cho_id BIGINT UNSIGNED NULL,\n  ket_qua_xu_ly TEXT NULL,\n  dong_luc DATETIME NULL,\n  tao_luc DATETIME NOT NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY uq_khieu_nai_ma (ma_khieu_nai),\n  KEY idx_khieu_nai_nguoi_gui (nguoi_gui_id, trang_thai, tao_luc),\n  CONSTRAINT fk_khieu_nai_nguoi_gui FOREIGN KEY (nguoi_gui_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE,\n  CONSTRAINT fk_khieu_nai_gan_cho FOREIGN KEY (gan_cho_id) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE khieu_nai_tin_nhan (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  khieu_nai_id BIGINT UNSIGNED NOT NULL,\n  nguoi_gui_id BIGINT UNSIGNED NOT NULL,\n  noi_dung TEXT NOT NULL,\n  tep_dinh_kem JSON NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_khieu_nai_tin_nhan (khieu_nai_id, tao_luc),\n  CONSTRAINT fk_khieu_nai_tin_nhan_khieu_nai FOREIGN KEY (khieu_nai_id) REFERENCES khieu_nai(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_khieu_nai_tin_nhan_nguoi_gui FOREIGN KEY (nguoi_gui_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE thong_bao (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  tai_khoan_id BIGINT UNSIGNED NOT NULL,\n  nguoi_gui_id BIGINT UNSIGNED NULL,\n  loai VARCHAR(80) NOT NULL,\n  tieu_de VARCHAR(191) NOT NULL,\n  noi_dung TEXT NOT NULL,\n  trang_thai ENUM('chua_doc', 'da_doc') NOT NULL DEFAULT 'chua_doc',\n  duong_dan_hanh_dong VARCHAR(500) NULL,\n  entity_type VARCHAR(80) NULL,\n  entity_id BIGINT UNSIGNED NULL,\n  tao_luc DATETIME NOT NULL,\n  doc_luc DATETIME NULL,\n  cap_nhat_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_thong_bao_tai_khoan_trang_thai (tai_khoan_id, trang_thai, tao_luc),\n  CONSTRAINT fk_thong_bao_tai_khoan FOREIGN KEY (tai_khoan_id) REFERENCES tai_khoan(id) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT fk_thong_bao_nguoi_gui FOREIGN KEY (nguoi_gui_id) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE audit_log (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  actor_id BIGINT UNSIGNED NULL,\n  actor_role VARCHAR(50) NULL,\n  action VARCHAR(120) NOT NULL,\n  resource_type VARCHAR(80) NOT NULL,\n  resource_id BIGINT UNSIGNED NULL,\n  old_value JSON NULL,\n  new_value JSON NULL,\n  ip_address VARCHAR(80) NULL,\n  user_agent TEXT NULL,\n  request_id VARCHAR(120) NULL,\n  tao_luc DATETIME NOT NULL,\n  PRIMARY KEY (id),\n  KEY idx_audit_resource (resource_type, resource_id, tao_luc),\n  KEY idx_audit_actor (actor_id, tao_luc),\n  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES tai_khoan(id) ON DELETE SET NULL ON UPDATE CASCADE\n)");
    await queryRunner.query("CREATE TABLE export_job (\n  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  nguoi_tao_id BIGINT UNSIGNED NOT NULL,\n  loai_export ENUM('doanh_thu', 'thanh_toan', 'hoa_hong', 'danh_gia', 'khieu_nai') NOT NULL,\n  dinh_dang ENUM('csv', 'xlsx', 'pdf') NOT NULL DEFAULT 'csv',\n  filter_json JSON NULL,\n  trang_thai ENUM('cho_xu_ly', 'dang_xu_ly', 'hoan_thanh', 'that_bai') NOT NULL DEFAULT 'cho_xu_ly',\n  file_url VARCHAR(500) NULL,\n  loi TEXT NULL,\n  tao_luc DATETIME NOT NULL,\n  hoan_thanh_luc DATETIME NULL,\n  PRIMARY KEY (id),\n  KEY idx_export_job_nguoi_tao (nguoi_tao_id, trang_thai, tao_luc),\n  CONSTRAINT fk_export_job_nguoi_tao FOREIGN KEY (nguoi_tao_id) REFERENCES tai_khoan(id) ON DELETE RESTRICT ON UPDATE CASCADE\n)");
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 0');
    await queryRunner.query('DROP TABLE IF EXISTS export_job');
    await queryRunner.query('DROP TABLE IF EXISTS audit_log');
    await queryRunner.query('DROP TABLE IF EXISTS thong_bao');
    await queryRunner.query('DROP TABLE IF EXISTS khieu_nai_tin_nhan');
    await queryRunner.query('DROP TABLE IF EXISTS khieu_nai');
    await queryRunner.query('DROP TABLE IF EXISTS chi_tra_hoa_hong');
    await queryRunner.query('DROP TABLE IF EXISTS chi_tiet_hoa_hong');
    await queryRunner.query('DROP TABLE IF EXISTS ky_hoa_hong');
    await queryRunner.query('DROP TABLE IF EXISTS cau_hinh_hoa_hong');
    await queryRunner.query('DROP TABLE IF EXISTS goi_y_dinh_duong_tap_luyen');
    await queryRunner.query('DROP TABLE IF EXISTS goi_y_suc_khoe');
    await queryRunner.query('DROP TABLE IF EXISTS tin_nhan_chat_ai');
    await queryRunner.query('DROP TABLE IF EXISTS phien_chat_ai');
    await queryRunner.query('DROP TABLE IF EXISTS phan_hoi_danh_gia');
    await queryRunner.query('DROP TABLE IF EXISTS danh_gia');
    await queryRunner.query('DROP TABLE IF EXISTS cuoc_goi_tu_van');
    await queryRunner.query('DROP TABLE IF EXISTS tin_nhan');
    await queryRunner.query('DROP TABLE IF EXISTS ghi_chu_tu_van');
    await queryRunner.query('DROP TABLE IF EXISTS booking_timeline');
    await queryRunner.query('DROP TABLE IF EXISTS lich_hen');
    await queryRunner.query('DROP TABLE IF EXISTS lich_ban_chuyen_gia');
    await queryRunner.query('DROP TABLE IF EXISTS lich_lam_viec_chuyen_gia');
    await queryRunner.query('DROP TABLE IF EXISTS refund');
    await queryRunner.query('DROP TABLE IF EXISTS payment_webhook_log');
    await queryRunner.query('DROP TABLE IF EXISTS thanh_toan');
    await queryRunner.query('DROP TABLE IF EXISTS lich_su_su_dung_goi');
    await queryRunner.query('DROP TABLE IF EXISTS goi_da_mua');
    await queryRunner.query('DROP TABLE IF EXISTS goi_dich_vu_chuyen_gia');
    await queryRunner.query('DROP TABLE IF EXISTS goi_dich_vu');
    await queryRunner.query('DROP TABLE IF EXISTS chuyen_gia');
    await queryRunner.query('DROP TABLE IF EXISTS otp');
    await queryRunner.query('DROP TABLE IF EXISTS chi_so_suc_khoe');
    await queryRunner.query('DROP TABLE IF EXISTS ho_so_suc_khoe');
    await queryRunner.query('DROP TABLE IF EXISTS ho_so_customer');
    await queryRunner.query('DROP TABLE IF EXISTS tai_khoan');
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 1');
  }
}
