import type { TableSeeder } from '../types';

const chuyen_giaSeeder: TableSeeder = {
  table: 'chuyen_gia',
  rows: [
    {
      id: 1, tai_khoan_id: 3,
      chuyen_mon: 'Dinh dưỡng lâm sàng',
      mo_ta: 'ThS Lê Minh Phương có hơn 8 năm kinh nghiệm tư vấn dinh dưỡng cho bệnh nhân mãn tính và người muốn cải thiện sức khoẻ tổng thể. Chuyên sâu về lập thực đơn cá nhân hoá và theo dõi chỉ số sức khoẻ.',
      kinh_nghiem: '8 năm tư vấn dinh dưỡng lâm sàng tại Bệnh viện Đại học Y Hà Nội và phòng khám tư.',
      hoc_vi: 'Thạc sĩ Dinh dưỡng - ĐH Y Hà Nội',
      chung_chi: 'Chứng chỉ Tư vấn Dinh dưỡng Lâm sàng (ISAK Level 2)',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.8, so_luot_danh_gia: 42, so_booking_hoan_thanh: 85,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-06 08:00:00',
      tao_luc: '2026-01-06 08:00:00', cap_nhat_luc: '2026-01-06 08:00:00', xoa_luc: null,
    },
    {
      id: 2, tai_khoan_id: 4,
      chuyen_mon: 'Dinh dưỡng nhi khoa & phụ nữ',
      mo_ta: 'BS Nguyễn Thu Hà chuyên tư vấn dinh dưỡng cho trẻ em, phụ nữ mang thai và sau sinh. Tốt nghiệp loại giỏi tại ĐH Y Dược TP.HCM, có nhiều năm làm việc tại khoa Nhi bệnh viện Nhi Đồng.',
      kinh_nghiem: '6 năm tại Khoa Dinh dưỡng - Bệnh viện Nhi Đồng 1.',
      hoc_vi: 'Bác sĩ Dinh dưỡng - ĐH Y Dược TP.HCM',
      chung_chi: 'Chứng chỉ Dinh dưỡng Nhi khoa, Chứng chỉ Lactation Counselor',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.9, so_luot_danh_gia: 67, so_booking_hoan_thanh: 120,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-06 08:00:00',
      tao_luc: '2026-01-06 08:00:00', cap_nhat_luc: '2026-01-06 08:00:00', xoa_luc: null,
    },
    {
      id: 3, tai_khoan_id: 5,
      chuyen_mon: 'Huấn luyện thể hình & dinh dưỡng thể thao',
      mo_ta: 'PT Trần Văn Khải là huấn luyện viên thể hình chuyên nghiệp với chứng chỉ quốc tế ACE-CPT. Chuyên xây dựng chương trình tập luyện kết hợp dinh dưỡng thể thao giúp khách hàng đạt mục tiêu nhanh và an toàn.',
      kinh_nghiem: '5 năm PT tại các gym lớn tại Hà Nội, chuyên gia Fitness Competition Prep.',
      hoc_vi: 'Cử nhân Thể dục Thể thao - ĐH TDTT Hà Nội',
      chung_chi: 'ACE Certified Personal Trainer, NASM Nutrition Coach',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.7, so_luot_danh_gia: 38, so_booking_hoan_thanh: 72,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-07 08:00:00',
      tao_luc: '2026-01-07 08:00:00', cap_nhat_luc: '2026-01-07 08:00:00', xoa_luc: null,
    },
    {
      id: 4, tai_khoan_id: 6,
      chuyen_mon: 'Dinh dưỡng giảm cân bền vững',
      mo_ta: 'ThS Phạm Ngọc Linh chuyên tư vấn giảm cân khoa học, không nhịn ăn. Tiếp cận hành vi thay đổi lối sống bền vững, kết hợp tâm lý ăn uống và dinh dưỡng cân bằng.',
      kinh_nghiem: '7 năm tư vấn giảm cân, đồng tác giả nhiều bài báo khoa học về béo phì.',
      hoc_vi: 'Thạc sĩ Dinh dưỡng & Sức khoẻ Cộng đồng - ĐH Y tế Công cộng',
      chung_chi: 'Chứng chỉ Obesity Management Specialist, Chứng chỉ Mindful Eating',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.6, so_luot_danh_gia: 55, so_booking_hoan_thanh: 95,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-08 08:00:00',
      tao_luc: '2026-01-08 08:00:00', cap_nhat_luc: '2026-01-08 08:00:00', xoa_luc: null,
    },
    {
      id: 5, tai_khoan_id: 7,
      chuyen_mon: 'Dinh dưỡng bệnh lý (tiểu đường, tim mạch)',
      mo_ta: 'TS Vũ Thị Mai Anh là chuyên gia hàng đầu về dinh dưỡng điều trị bệnh tiểu đường type 2, tim mạch và tăng huyết áp. Đã trực tiếp tư vấn cho hơn 200 bệnh nhân mãn tính.',
      kinh_nghiem: '10 năm nghiên cứu và tư vấn lâm sàng tại Viện Dinh dưỡng Quốc gia.',
      hoc_vi: 'Tiến sĩ Dinh dưỡng - Đại học Tokyo (Nhật Bản)',
      chung_chi: 'Certified Diabetes Care and Education Specialist (CDCES)',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.9, so_luot_danh_gia: 88, so_booking_hoan_thanh: 160,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-06 08:00:00',
      tao_luc: '2026-01-06 08:00:00', cap_nhat_luc: '2026-01-06 08:00:00', xoa_luc: null,
    },
    {
      id: 6, tai_khoan_id: 8,
      chuyen_mon: 'Phục hồi chức năng & dinh dưỡng vận động viên',
      mo_ta: 'BS Đỗ Thanh Bình chuyên tư vấn phục hồi sau chấn thương kết hợp dinh dưỡng tối ưu cho vận động viên. Từng làm việc với đội tuyển thể thao quốc gia.',
      kinh_nghiem: '9 năm trong lĩnh vực y học thể thao và phục hồi chức năng.',
      hoc_vi: 'Bác sĩ Y học Thể thao - ĐH Y Hà Nội',
      chung_chi: 'Chứng chỉ Sports Medicine Physician, ACSM',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: false,
      diem_danh_gia_trung_binh: 4.5, so_luot_danh_gia: 29, so_booking_hoan_thanh: 55,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-09 08:00:00',
      tao_luc: '2026-01-09 08:00:00', cap_nhat_luc: '2026-01-09 08:00:00', xoa_luc: null,
    },
    {
      id: 7, tai_khoan_id: 9,
      chuyen_mon: 'Dinh dưỡng tổng quát',
      mo_ta: 'CN Hoàng Bảo Trâm mới tốt nghiệp, đang chờ duyệt hồ sơ chuyên gia để bắt đầu tư vấn.',
      kinh_nghiem: '1 năm thực tập tại phòng khám dinh dưỡng.',
      hoc_vi: 'Cử nhân Dinh dưỡng - ĐH Y tế Công cộng',
      chung_chi: 'Chứng chỉ Tư vấn Dinh dưỡng cơ bản',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'cho_duyet', nhan_booking: false,
      diem_danh_gia_trung_binh: 0, so_luot_danh_gia: 0, so_booking_hoan_thanh: 0,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: null, duyet_luc: null,
      tao_luc: '2026-04-20 08:00:00', cap_nhat_luc: '2026-04-20 08:00:00', xoa_luc: null,
    },
    {
      id: 8, tai_khoan_id: 10,
      chuyen_mon: 'Dinh dưỡng người cao tuổi & phòng ngừa lão hoá',
      mo_ta: 'ThS Lý Quốc Bảo chuyên tư vấn dinh dưỡng phòng ngừa lão hoá, tăng cường miễn dịch và hỗ trợ sức khoẻ xương khớp cho người trên 50 tuổi.',
      kinh_nghiem: '6 năm tư vấn tại Trung tâm Chăm sóc Sức khoẻ Người cao tuổi.',
      hoc_vi: 'Thạc sĩ Dinh dưỡng Lão khoa - ĐH Y Dược TP.HCM',
      chung_chi: 'Certified Geriatric Nutrition Specialist',
      anh_dai_dien_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
      trang_thai: 'hoat_dong', nhan_booking: true,
      diem_danh_gia_trung_binh: 4.7, so_luot_danh_gia: 33, so_booking_hoan_thanh: 61,
      ly_do_tu_choi: null, ly_do_bi_khoa: null,
      duyet_boi: 1, duyet_luc: '2026-01-10 08:00:00',
      tao_luc: '2026-01-10 08:00:00', cap_nhat_luc: '2026-01-10 08:00:00', xoa_luc: null,
    },
  ],
};

export default chuyen_giaSeeder;
