import type { TableSeeder } from '../types';

const ho_so_suc_khoeSeeder: TableSeeder = {
  table: 'ho_so_suc_khoe',
  rows: [
    {
      id: 1, tai_khoan_id: 11, gioi_tinh: 'nu', ngay_sinh: '1995-03-12',
      chieu_cao_cm: 158, can_nang_hien_tai_kg: 62,
      muc_do_van_dong: 'van_dong_nhe', muc_tieu_suc_khoe: 'giam_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['it_duong'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Muốn giảm vùng bụng và đùi là chính.',
      da_hoan_thanh: true, tao_luc: '2026-01-15 09:00:00', cap_nhat_luc: '2026-01-15 09:00:00',
    },
    {
      id: 2, tai_khoan_id: 12, gioi_tinh: 'nam', ngay_sinh: '1990-07-22',
      chieu_cao_cm: 172, can_nang_hien_tai_kg: 85,
      muc_do_van_dong: 'it_van_dong', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: ['tieu_duong_type2'] },
      di_ung: [], che_do_an_uu_tien: ['it_duong', 'it_tinh_bot'], thuc_pham_khong_dung: ['banh_mi_trang'],
      ghi_chu_cho_chuyen_gia: 'Đường huyết dao động, cần thực đơn ổn định đường huyết.',
      da_hoan_thanh: true, tao_luc: '2026-01-20 09:00:00', cap_nhat_luc: '2026-01-20 09:00:00',
    },
    {
      id: 3, tai_khoan_id: 13, gioi_tinh: 'nu', ngay_sinh: '1998-11-05',
      chieu_cao_cm: 163, can_nang_hien_tai_kg: 68,
      muc_do_van_dong: 'van_dong_nhe', muc_tieu_suc_khoe: 'giam_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: ['hai_san'], che_do_an_uu_tien: ['giau_sat', 'giau_protein'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Đang cho con bú, cần đảm bảo đủ dinh dưỡng cho mẹ và bé.',
      da_hoan_thanh: true, tao_luc: '2026-02-01 09:00:00', cap_nhat_luc: '2026-02-01 09:00:00',
    },
    {
      id: 4, tai_khoan_id: 14, gioi_tinh: 'nam', ngay_sinh: '1985-05-18',
      chieu_cao_cm: 175, can_nang_hien_tai_kg: 70,
      muc_do_van_dong: 'rat_nang_dong', muc_tieu_suc_khoe: 'tang_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['giau_protein', 'giau_carb'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Muốn đạt 80kg cơ bắp, cần thực đơn bulking.',
      da_hoan_thanh: true, tao_luc: '2026-01-10 09:00:00', cap_nhat_luc: '2026-01-10 09:00:00',
    },
    {
      id: 5, tai_khoan_id: 15, gioi_tinh: 'nu', ngay_sinh: '2001-09-30',
      chieu_cao_cm: 160, can_nang_hien_tai_kg: 52,
      muc_do_van_dong: 'it_van_dong', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: ['sua_bo'], che_do_an_uu_tien: ['it_duong'], thuc_pham_khong_dung: ['sua_bo'],
      ghi_chu_cho_chuyen_gia: 'Hay bị mệt mỏi vào buổi chiều, nghi là thiếu sắt.',
      da_hoan_thanh: true, tao_luc: '2026-02-10 09:00:00', cap_nhat_luc: '2026-02-10 09:00:00',
    },
    {
      id: 6, tai_khoan_id: 16, gioi_tinh: 'nam', ngay_sinh: '1978-01-14',
      chieu_cao_cm: 168, can_nang_hien_tai_kg: 88,
      muc_do_van_dong: 'it_van_dong', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: ['tang_huyet_ap', 'mo_mau_cao'] },
      di_ung: [], che_do_an_uu_tien: ['it_muoi', 'it_mo', 'nhieu_rau'], thuc_pham_khong_dung: ['do_an_nhanh'],
      ghi_chu_cho_chuyen_gia: 'Đang uống thuốc huyết áp, muốn cải thiện qua chế độ ăn.',
      da_hoan_thanh: true, tao_luc: '2026-01-25 09:00:00', cap_nhat_luc: '2026-01-25 09:00:00',
    },
    {
      id: 7, tai_khoan_id: 17, gioi_tinh: 'nu', ngay_sinh: '1992-06-27',
      chieu_cao_cm: 165, can_nang_hien_tai_kg: 55,
      muc_do_van_dong: 'rat_nang_dong', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['giau_protein', 'it_mo'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Chạy 10km 3 lần/tuần, cần dinh dưỡng cho marathon.',
      da_hoan_thanh: true, tao_luc: '2026-02-05 09:00:00', cap_nhat_luc: '2026-02-05 09:00:00',
    },
    {
      id: 8, tai_khoan_id: 18, gioi_tinh: 'nam', ngay_sinh: '1988-12-03',
      chieu_cao_cm: 170, can_nang_hien_tai_kg: 78,
      muc_do_van_dong: 'it_van_dong', muc_tieu_suc_khoe: 'giam_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['it_tinh_bot'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Hay ăn vặt buổi tối sau giờ làm.',
      da_hoan_thanh: true, tao_luc: '2026-03-01 09:00:00', cap_nhat_luc: '2026-03-01 09:00:00',
    },
    {
      id: 9, tai_khoan_id: 19, gioi_tinh: 'nu', ngay_sinh: '1996-04-08',
      chieu_cao_cm: 162, can_nang_hien_tai_kg: 55,
      muc_do_van_dong: 'van_dong_vua', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: ['IBS'] },
      di_ung: ['gluten'], che_do_an_uu_tien: ['it_lactose', 'nhieu_chat_xo'], thuc_pham_khong_dung: ['lua_mi', 'sua'],
      ghi_chu_cho_chuyen_gia: 'Cần chế độ ăn low-FODMAP phù hợp với IBS.',
      da_hoan_thanh: true, tao_luc: '2026-02-20 09:00:00', cap_nhat_luc: '2026-02-20 09:00:00',
    },
    {
      id: 10, tai_khoan_id: 20, gioi_tinh: 'nam', ngay_sinh: '1970-08-15',
      chieu_cao_cm: 167, can_nang_hien_tai_kg: 72,
      muc_do_van_dong: 'van_dong_nhe', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: ['loang_xuong_nhe'] },
      di_ung: [], che_do_an_uu_tien: ['giau_canxi', 'nhieu_rau'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Mật độ xương thấp, cần bổ sung canxi và vitamin D.',
      da_hoan_thanh: true, tao_luc: '2026-01-18 09:00:00', cap_nhat_luc: '2026-01-18 09:00:00',
    },
    {
      id: 11, tai_khoan_id: 21, gioi_tinh: 'nu', ngay_sinh: '2000-02-14',
      chieu_cao_cm: 161, can_nang_hien_tai_kg: 50,
      muc_do_van_dong: 'van_dong_vua', muc_tieu_suc_khoe: 'giu_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['thuc_pham_thuan_chay'], thuc_pham_khong_dung: ['thit', 'ca'],
      ghi_chu_cho_chuyen_gia: 'Ăn chay toàn phần (vegan), lo ngại thiếu B12 và sắt.',
      da_hoan_thanh: true, tao_luc: '2026-03-05 09:00:00', cap_nhat_luc: '2026-03-05 09:00:00',
    },
    {
      id: 12, tai_khoan_id: 22, gioi_tinh: 'nam', ngay_sinh: '1993-10-20',
      chieu_cao_cm: 180, can_nang_hien_tai_kg: 78,
      muc_do_van_dong: 'rat_nang_dong', muc_tieu_suc_khoe: 'cai_thien_suc_khoe',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['giau_carb', 'giau_protein'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Tập bơi cường độ cao, cần nạp năng lượng trước và sau tập.',
      da_hoan_thanh: true, tao_luc: '2026-02-15 09:00:00', cap_nhat_luc: '2026-02-15 09:00:00',
    },
    {
      id: 13, tai_khoan_id: 23, gioi_tinh: 'nu', ngay_sinh: '1987-07-11',
      chieu_cao_cm: 156, can_nang_hien_tai_kg: 65,
      muc_do_van_dong: 'van_dong_nhe', muc_tieu_suc_khoe: 'giam_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['it_duong', 'nhieu_rau'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Hormone thay đổi gây tăng cân nhanh và khó giảm.',
      da_hoan_thanh: true, tao_luc: '2026-03-10 09:00:00', cap_nhat_luc: '2026-03-10 09:00:00',
    },
    {
      id: 14, tai_khoan_id: 24, gioi_tinh: 'nam', ngay_sinh: '1999-12-25',
      chieu_cao_cm: 173, can_nang_hien_tai_kg: 68,
      muc_do_van_dong: 'nang_dong', muc_tieu_suc_khoe: 'tang_can',
      tinh_trang_suc_khoe: { benhNen: [] },
      di_ung: [], che_do_an_uu_tien: ['giau_protein'], thuc_pham_khong_dung: [],
      ghi_chu_cho_chuyen_gia: 'Tập gym 5 buổi/tuần, muốn đạt 76kg sau 3 tháng.',
      da_hoan_thanh: true, tao_luc: '2026-03-15 09:00:00', cap_nhat_luc: '2026-03-15 09:00:00',
    },
  ],
};

export default ho_so_suc_khoeSeeder;
